name: Build WPF App

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  

    - name: Restore dependencies
      run: dotnet restore

    - name: Build WPF project
      run: dotnet build --configuration Release
